# before_install: sudo apt-get install redis-server libmemcache-dev memcached
install:
  - gem update --system
  - bundle update
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx
  - ruby-head

notifications:
  irc: "irc.freenode.org#padrino"
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - d.dagostino@lipsiasoft.com
    - florian.gilcher@asquera.de

branches:
  only:
    - master
