# http://about.travis-ci.org/docs/user/build-configuration/
before_script: "git submodule update --init"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - rbx-2.0
  - ruby-head

notifications:
  irc: "irc.freenode.org#padrino"
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - d.dagostino@lipsiasoft.com
    - florian.gilcher@asquera.de

branches:
  only:
    - master