lang: ruby
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-18mode
  - jruby-19mode
notifications:
  irc: 'irc.freenode.org#padrino'
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - info@daddye.it
    - florian.gilcher@asquera.de
    - dario@uxtemple.com
    - ujifgc@gmail.com
    - ortuna@gmail.com
branches:
  only:
    - master
services: mongodb
matrix:
  include:
    - rvm: 1.9.3
      env: SINATRA_EDGE=true
    - rvm: 1.9.3
      env: AS_VERSION=3.1.0
    - rvm: 2.0.0
      env: SINATRA_EDGE=true
    - rvm: 2.0.0
      env: AS_VERSION=3.1.0
  allow_failures:
    - rvm: 1.9.3
      env: SINATRA_EDGE=true
    - rvm: 2.0.0
      env: SINATRA_EDGE=true
    - rvm: rbx-18mode
