lang: ruby
before_install: gem install bundler --pre
install:
  - gem update --system
  - bundle update
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx-2
  - jruby
notifications:
  irc: 'irc.freenode.org#padrino'
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - info@daddye.it
    - florian.gilcher@asquera.de
    - dario@uxtemple.com
    - ujifgc@gmail.com
    - ortuna@gmail.com
    - namusyaka@gmail.com
branches:
  only:
    - master
services: mongodb
matrix:
  include:
    - rvm: 2.1.1
      env: SINATRA_EDGE=true
  allow_failures:
    - rvm: 2.1.1
      env: SINATRA_EDGE=true
