language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler
install:
  - bundle update
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2.2
  - 2.3.1
  - rbx-2
  - jruby-9.0.5.0
  - ruby-head
  - jruby-head
notifications:
  irc: 'irc.freenode.org#padrino'
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - info@daddye.it
    - florian.gilcher@asquera.de
    - dario@uxtemple.com
    - ujifgc@gmail.com
    - ortuna@gmail.com
    - namusyaka@gmail.com
branches:
  only:
    - master
    - 0.12
services: mongodb
matrix:
  include:
    - rvm: 2.2.2
      env: SINATRA_EDGE=true
    - rvm: 2.1
      env: STDLIB_ERB=true
    - rvm: 2.1
      env: AS_VERSION=3.2
    - rvm: jruby
      env: AS_VERSION=4.2
  allow_failures:
    - rvm: jruby-9.0.5.0
    - rvm: rbx-2
    - env: SINATRA_EDGE=true
    - rvm: ruby-head
    - rvm: jruby-head
