language: ruby
sudo: false
cache: bundler
before_install:
  - gem install bundler
install:
  - bundle update
rvm:
  - 2.2.2
  - 2.3.0
  - 2.3.3
  - 2.4.3
  - 2.5.0
  - ruby-head
  - rbx-2
  - jruby
  - jruby-head
notifications:
  irc: 'irc.freenode.org#padrino'
  recipients:
    - nesquena@gmail.com
    - mr.arthur.chiu@gmail.com
    - joshbuddy@gmail.com
    - info@daddye.it
    - florian.gilcher@asquera.de
    - dario@uxtemple.com
    - ujifgc@gmail.com
    - ortuna@gmail.com
    - namusyaka@gmail.com
branches:
  only:
    - master
    - 0.12
    - 0.14
services: mongodb
matrix:
  include:
    - rvm: 2.3.3
      env: SINATRA_EDGE=true
    - rvm: 2.3.3
      env: ERB_ENGINE=stdlib
    - rvm: 2.3.3
      env: ERB_ENGINE=erubis
    - rvm: 2.3.3
      env: HAML_ENGINE=hamlit
    - rvm: 2.3.3
      env: AS_VERSION=3.2
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby
    - rvm: jruby-head
    - rvm: ruby-head
    - env: SINATRA_EDGE=true
